from __future__ import annotations

import hashlib
import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from app.config import settings
from app.logging_config import log_event
from app.schemas.generation_request import GenerationRequest
from app.schemas.generation_result import GenerationResult
from app.schemas.idempotency import IdempotencyRecord
from app.schemas.repository_inventory import RepositoryInventory

logger = logging.getLogger(__name__)


class IdempotencyService:
    """Prevent the same story from being generated twice against the same repo.

    The fingerprint hashes the repository version (head + file hashes) together
    with the story inputs. A repeated Generate click before the repository
    changes hits the registry and returns the previous outcome instead of
    appending an identical test again.
    """

    def __init__(self, registry_root: str | None = None) -> None:
        self.registry_path = (
            Path(registry_root or settings.workspace_root)
            / "test-agent-workspaces"
            / "idempotency-registry.json"
        )

    def fingerprint(
        self, request: GenerationRequest, inventory: RepositoryInventory
    ) -> str:
        digest = hashlib.sha256()
        digest.update(str(Path(request.repo_path).resolve()).encode())
        digest.update((inventory.repo_head or "").encode())
        for path in sorted(inventory.file_hashes):
            digest.update(f"{path}:{inventory.file_hashes[path]}\n".encode())
        digest.update(request.test_case_name.encode())
        for step in request.steps:
            digest.update(step.encode())
        return digest.hexdigest()[:32]

    def find(self, fingerprint: str) -> IdempotencyRecord | None:
        registry = self._load()
        record = registry.get(fingerprint)
        if record is None:
            return None
        found = IdempotencyRecord.model_validate(record)
        log_event(
            logger,
            logging.INFO,
            "idempotency",
            "duplicate_generation_detected",
            fingerprint=fingerprint,
            original_job=found.job_id,
            completed_at=found.completed_at,
        )
        return found

    def record(self, fingerprint: str, result: GenerationResult) -> None:
        if not result.files_changed:
            return
        registry = self._load()
        registry[fingerprint] = IdempotencyRecord(
            fingerprint=fingerprint,
            job_id=result.job_id,
            completed_at=datetime.now(timezone.utc).isoformat(),
            files_changed=result.files_changed,
            diff_summary=result.diff_summary,
        ).model_dump()
        self.registry_path.parent.mkdir(parents=True, exist_ok=True)
        self.registry_path.write_text(
            json.dumps(registry, indent=2), encoding="utf-8"
        )
        log_event(
            logger,
            logging.INFO,
            "idempotency",
            "recorded",
            fingerprint=fingerprint,
            job_id=result.job_id,
        )

    def replay_result(
        self, request: GenerationRequest, record: IdempotencyRecord
    ) -> GenerationResult:
        return GenerationResult(
            job_id=request.job_id,
            files_changed=[],
            diff_summary=(
                "Equivalent patch already generated by job "
                f"{record.job_id} at {record.completed_at}; nothing new applied."
            ),
            diff="",
            confidence=1.0,
            needs_review=False,
            review_reasons=[],
            idempotent_replay=True,
            replayed_from_job=record.job_id,
            generation_fingerprint=record.fingerprint,
        )

    def _load(self) -> dict[str, dict]:
        try:
            return json.loads(self.registry_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return {}
